//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about_us
    {
        public int ID { get; set; }
        public string sort_description_home { get; set; }
        public string full_description { get; set; }
        public string about_image { get; set; }
        public string about_image_home { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
