//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about_ourvision
    {
        public int ID { get; set; }
        public string title1 { get; set; }
        public string sort_description1 { get; set; }
        public string image_1 { get; set; }
        public string title2 { get; set; }
        public string sort_description2 { get; set; }
        public string image_2 { get; set; }
        public System.DateTime created_at { get; set; }
        public string image_file { get; set; }
    }
}
