//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Benitton_dbEntities : DbContext
{
    public Benitton_dbEntities()
        : base("name=Benitton_dbEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<about_certification> about_certification { get; set; }
    public DbSet<about_ourvalues> about_ourvalues { get; set; }
    public DbSet<about_ourvision> about_ourvision { get; set; }
    public DbSet<about_us> about_us { get; set; }
    public DbSet<contact_detail> contact_detail { get; set; }
    public DbSet<contact_us> contact_us { get; set; }
    public DbSet<sale_support> sale_support { get; set; }
    public DbSet<tbl_admin> tbl_admin { get; set; }
    public DbSet<Tbl_blog> Tbl_blog { get; set; }
    public DbSet<tbl_career> tbl_career { get; set; }
    public DbSet<tbl_category> tbl_category { get; set; }
    public DbSet<Tbl_Contact> Tbl_Contact { get; set; }
    public DbSet<Tbl_faq> Tbl_faq { get; set; }
    public DbSet<tbl_product> tbl_product { get; set; }
    public DbSet<Tbl_saleSupportBannes> Tbl_saleSupportBannes { get; set; }
    public DbSet<Tbl_subCategory> Tbl_subCategory { get; set; }
    public DbSet<tbl_subscribe> tbl_subscribe { get; set; }
    public DbSet<tbl_testimonial> tbl_testimonial { get; set; }
    public DbSet<Tbl_banner> Tbl_banner { get; set; }
    public DbSet<product_enq> product_enq { get; set; }
    public DbSet<tbl_Menu> tbl_Menu { get; set; }
}
