//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_detail
    {
        public int ID { get; set; }
        public string sort_description { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public string office_address { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
