//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_enq
    {
        public int ID { get; set; }
        public string organisation_name { get; set; }
        public string contact_name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string product_title { get; set; }
        public string product_url { get; set; }
        public string message_detail { get; set; }
        public System.DateTime created_at { get; set; }
        public string state { get; set; }
    }
}
