//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_support
    {
        public int complaint_id { get; set; }
        public string equipment_make { get; set; }
        public long serial_no { get; set; }
        public string customer_company { get; set; }
        public string contact_person { get; set; }
        public string email { get; set; }
        public string problem_type { get; set; }
        public string urgency_level { get; set; }
        public string equipment_model { get; set; }
        public string meter_radio { get; set; }
        public string meter_number { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string nature_problem { get; set; }
        public string position { get; set; }
        public string complaint_number { get; set; }
        public string equipment_description { get; set; }
        public bool status { get; set; }
        public System.DateTime created_at { get; set; }
        public string attachment { get; set; }
        public string ticket_number { get; set; }
    }
}
