//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public int id { get; set; }
        public string name { get; set; }
        public string emailid { get; set; }
        public string password { get; set; }
        public string mobile_no { get; set; }
        public System.DateTime created_at { get; set; }
        public string user_type { get; set; }
    }
}
