//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category
    {
        public int ID { get; set; }
        public int MenuID { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public System.DateTime created_at { get; set; }
        public string image_file { get; set; }
        public bool Isdelete { get; set; }
    }
}
