//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benitton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public int Qty { get; set; }
        public int Price { get; set; }
        public string Detail { get; set; }
        public string Image_1 { get; set; }
        public string Image_2 { get; set; }
        public string Image_3 { get; set; }
        public string Image_4 { get; set; }
        public bool Isactive { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public bool display_on_home { get; set; }
        public string Image_5 { get; set; }
        public string Image_6 { get; set; }
        public string Image_7 { get; set; }
        public string Image_8 { get; set; }
        public string salient_features { get; set; }
        public string specifications { get; set; }
        public string pdf_image { get; set; }
        public string sale_status { get; set; }
        public bool Isdelete { get; set; }
        public Nullable<int> serialorder { get; set; }
        public Nullable<int> otherCatID { get; set; }
        public string video_iframe { get; set; }
        public string optional_ddetail { get; set; }
        public string home_image { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Keywords { get; set; }
        public string Meta_Canical { get; set; }
        public string Meta_description { get; set; }
    }
}
